### ISSUE TITLE
TBB can't launch with private-lib and private-bin

### ISSUE THREAD

**Issue by samsapti** [rusty-snake/firejailed-tor-browser#33]
When running `firejail --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"`, I'm getting this error:
```
/home/user/Browser/start-tor-browser: line 94: id: command not found
/home/user/Browser/start-tor-browser: line 94: [: : integer expression expected
```

System information:
- OS: Artix Linux
- Windowing system: Wayland
- WM: Sway
- XWayland installed: No
- Firejail version: git (`firejail-git` from the AUR)
- Tor  Browser version: 10.5.6

Launching Tor Browser without firejail however works fine with env vars `DISPLAY=Wayland` and `MOZ_ENABLE_WAYLAND=1`.

Full output of `firejail --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` is attached.

[firejailed-tor-browser.log](https://github.com/rusty-snake/firejailed-tor-browser/files/7150276/firejailed-tor-browser.log)

**Comment by rusty-snake** [comment]
`/bin/id` is used to make sure you don't start the tor browser as root.

```bash
if [ "`id -u`" -eq 0 ]; then
    complain "The Tor Browser Bundle should not be run as root.  Exiting."
    exit 1
fi
```

However, since we don't do that anyway, we can harden private-bin further by removing `id`.

**Comment by samsapti** [comment]
@rusty-snake are you saying we should remove the mentioned snippet from `start-tor-browser`? I don't think we should mess with the Tor Browser startup script more than strictly necessary.

**Comment by rusty-snake** [comment]
No. I already known this error. But it is only a cosmetic bug. That's what I wanted to point out.

**Comment by samsapti** [comment]
Okay, but how should I solve the issue that Tor Browser can't launch with Firejail?

**Comment by rusty-snake** [comment]
Wait, it does not launch for you. Didn't got this from OP. Anyway, assuming it launched previously, can you try which change is causing this (my guesses: `private-lib` or minimized wusc).

- `firejail --ignore=private-lib --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"`
- `firejail --profile=firejailed-tor-browser --include=/etc/firejail/whitelist-usr-share-common.inc "$HOME/Browser/start-tor-browser"`

**Comment by samsapti** [comment]
@rusty-snake all of them gives the same error.

**Comment by rusty-snake** [comment]
and other changes (e.g. `blacklist /tmp`)?

The "id: command not found" error is show at startup since 2 years.

**Comment by samsapti** [comment]
> and other changes (e.g. `blacklist /tmp`)?
> 
> The "id: command not found" error is show at startup since 2 years.

@rusty-snake I've tried commenting / uncommenting every line in `firejailed-tor-browser.profile`, here are my findings:

- Removing `shell none` on line 102 makes the error message disappear, but causes a new error message:
```
Cannot start application: No such file or directory
```
- Removing `private ${HOME}/.firejailed-tor-browser` on line 105 makes the error message disappear, causes the following error:
```
Error: no suitable /home/user/Browser/start-tor-browser executable found
```
- Removing `private-bin bash,dirname,env,expr,file,grep,rm,sh` on line 106 makes the error message disappear, but causes the following error:
```
bash: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory
```

Still, I couldn't launch Tor Browser.

**Comment by rusty-snake** [comment]
Removing `shell none` or `private` will results in these errors (that's what to expect).
Removing `private-bin` will has an effect on `private-lib`.

> I've tried commenting / uncommenting every line in 

One for one or also at the same time (i.e. the "need to comment A and B" case is covered)?

Just to be sure, `firejail --noprofile --private=${HOME}/.firejailed-tor-browser --shell=none --env=MOZ_ENABLE_WAYLAND=1 "$HOME/Browser/start-tor-browser"` launches?

Do you use something other than bash as login shell (e.g. fish)?

**Comment by rusty-snake** [comment]
What does `echo $XDG_RUNTIME_DIR` show? (Asking because of https://github.com/netblue30/firejail/issues/4535)

**Comment by samsapti** [comment]
> Removing `shell none` or `private` will results in these errors (that's what to expect).
> Removing `private-bin` will has an effect on `private-lib`.
> 
> > I've tried commenting / uncommenting every line in
> 
> One for one or also at the same time (i.e. the "need to comment A and B" case is covered)?

I only tried one for one, I'm not familiar enough with firejail profile files to know what I can and can't do.

> Just to be sure, `firejail --noprofile --private=${HOME}/.firejailed-tor-browser --shell=none --env=MOZ_ENABLE_WAYLAND=1 "$HOME/Browser/start-tor-browser"` launches?

Works fine after adding `--env=DISPLAY=foo`, otherwise it complains that Tor Browser must run in X.

> Do you use something other than bash as login shell (e.g. fish)?

I use `zsh`.

> What does `echo $XDG_RUNTIME_DIR` show? (Asking because of [netblue30/firejail#4535](https://github.com/netblue30/firejail/issues/4535))

```
/run/user/1000
```

**Comment by samsapti** [comment]
But `echo $RUNUSER` returns nothing.

**Comment by rusty-snake** [comment]
> > Removing `shell none` or `private` will results in these errors (that's what to expect).
> > Removing `private-bin` will has an effect on `private-lib`.
> > > I've tried commenting / uncommenting every line in
> > 
> > 
> > One for one or also at the same time (i.e. the "need to comment A and B" case is covered)?
> 
> I only tried one for one, I'm not familiar enough with firejail profile files to know what I can and can't do.
> 
> > Just to be sure, `firejail --noprofile --private=${HOME}/.firejailed-tor-browser --shell=none --env=MOZ_ENABLE_WAYLAND=1 "$HOME/Browser/start-tor-browser"` launches?
> 
> Works fine after adding `--env=DISPLAY=foo`, otherwise it complains that Tor Browser must run in X.

Then comment everything (except for `private ${HOME}/...` and `shell none`) and uncomment it line for line (for `whitelist` you can uncomment a full prefix (e.g. `/usr/share`) at once).

**Comment by samsapti** [comment]
@rusty-snake it seems that `private-bin bash,dirname,env,expr,file,grep,rm,sh` (line 106) is the issue. As soon as I uncommented that, it gave the `id` error. I tried adding `id` to the end of the line (so it reads `...,rm,sh,id`), now it just quits without an error message, Tor Browser doesn't show up.

EDIT: `apparmor` causes it not to launch as well.

**Comment by rusty-snake** [comment]
The `id` error exists for 2 years and it actually doing nothing than priting 2 lines. The only recent change to `private-bin` was the removal of `tclsh` but it `blacklist`ed.

> `appamor`

Why did I added `apprmor`? It can not work.

**Comment by samsapti** [comment]
I mean, everything seemed to work on my previous Linux install (Manjaro, with X), I just recently installed Artix and Wayland and ran into these problems, even with `apparmor`.

**Comment by rusty-snake** [comment]
So if you remove `apparmor` (2645bbb) and execute `firejail --ignore=private-bin --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` it works? If so, run `firejail --trace=tbb.trace --ignore=private-bin --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` and `grep bin tbb.trace` to find which binaries are required.

**Comment by samsapti** [comment]
> So if you remove `apparmor` ([2645bbb](https://github.com/rusty-snake/firejailed-tor-browser/commit/2645bbb04ef106af004072825450c86caafc5f84)) and execute `firejail --ignore=private-bin --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` it works?

Yes, with `--ignore=private-lib` too.

> If so, run `firejail --trace=tbb.trace --ignore=private-bin --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` and `grep bin tbb.trace` to find which binaries are required.

It gives me this error:

```
Error mount bind ld.so.preload: fs_trace.c:110 fs_trace: No such file or directory
Error: proc 28768 cannot sync with peer: unexpected EOF
Peer 28769 unexpectedly exited with status 1
```

`tbb.trace` is empty.

**Comment by rusty-snake** [comment]
> Yes, with --ignore=private-lib too.

`ignore` private-bin and -lib?

> Error mount bind ld.so.preload: fs_trace.c:110 fs_trace: No such file or directory

`--noblacklist=/etc`

**Comment by samsapti** [comment]
> `ignore` private-bin and -lib?

Yes.

> `--noblacklist=/etc`

That worked. [missing-bins.txt](https://github.com/rusty-snake/firejailed-tor-browser/files/7180789/missing-bins.txt)

**Comment by rusty-snake** [comment]
If `--ignore=private-lib --private-bin=sed,getconf` works, try if only `sed` or ony `getconf` is enough.

**Comment by samsapti** [comment]
> If `--ignore=private-lib --private-bin=sed,getconf` works, try if only `sed` or ony `getconf` is enough.

Okay, it still prints the `id` error, but Tor Browser launches now. It works without `sed`.

My `firejailed-tor-browser.profile` works if I add `getconf` to `private-bin` and comment out `private-lib`, though it still prints the `id` error.
