### ISSUE TITLE
FTB won't start when /bin/sh is dash

### ISSUE THREAD

**Issue by samsapti** [rusty-snake/firejailed-tor-browser#34]
# Description

FTB won't start when `/bin/sh` is symlinked to `dash` instead of `bash`, despite the `#!/usr/bin/env bash` hash bang in `~/.firejailed-tor-browser/Browser/start-tor-browser`. It works fine if I run `~/.firejailed-tor-browser/Browser/start-tor-browser` or `~/.firejailed-tor-browser/start-tor-browser.desktop` directly without Firejail. Also, other applications work fine with Firejail. I also tried changing the `Exec=sh -c {...}` to `Exec=bash -c {...}` in both `~/.firejailed-tor-browser/start-tor-browser.desktop` and `.local/share/applications/firejailed-tor-browser.desktop`, but with no luck.

# Steps to reproduce

- Symlink `/bin/sh` to `/bin/dash`
- Run FTB with `firejail --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"`

# System info

- OS: Artix Linux
- Display server: Wayland
- Firejail version: 0.9.66
- Tor Browser version: 11.0.3

**Comment by rusty-snake** [comment]
https://github.com/rusty-snake/firejailed-tor-browser/blob/249d337c91325fc7b26ab2bc1253132d3d5faa47/firejailed-tor-browser.profile#L48-L49

should be replaced with `include allow-bin-sh.inc`.

**Comment by samsapti** [comment]
> https://github.com/rusty-snake/firejailed-tor-browser/blob/249d337c91325fc7b26ab2bc1253132d3d5faa47/firejailed-tor-browser.profile#L48-L49
> 
> should be replaced with `include allow-bin-sh.inc`.

Simply adding `include include allow-bin-sh.inc` without removing the other two lines solved the problem. Removing either of the `noblacklist` lines broke it. Removing the `bash` one caused `/usr/bin/env: ‘bash’: Permission denied`, probably because of the hash bang in `~/.firejailed-tor-browser/Browser/start-tor-browser`.

Thanks!

NOTE: I'm using the `v0.9.66` backport.

EDIT: I think it broke because I used `ignore noblacklist {...}` for the two lines there in my `firejailed-tor-browser.local`.
