### ISSUE TITLE
Won't start on Debian 11.3

### ISSUE THREAD

**Issue by wonbug** [rusty-snake/firejailed-tor-browser#37]
Fresh Debian 11.3 install, grabbed `tor-browser-linux64-11.0.10_en-US.tar.xz` and cloned this repository, ran the install script.

```
$ firejail --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser" --name="Tor Browser"
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser.profile
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser.local
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser-x11.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/allow-bin-sh.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Error: cannot access profile file: disable-proc.inc

$ firejail --version
firejail version 0.9.64.4
```

No luck with the stable profile either:

```
$ cp ~/git/firejailed-tor-browser/stable-profiles/0.9.64.4/* ~/.config/firejail

$ firejail --profile=firejailed-tor-browser /home/wonbug/Browser/start-tor-browser
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser.profile
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser.local
Reading profile /home/wonbug/.config/firejail/firejailed-tor-browser-x11.inc
Reading profile /etc/firejail/allow-bin-sh.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /home/wonbug/.config/firejail/disable-programs.local
Reading profile /etc/firejail/disable-shell.inc
Reading profile /etc/firejail/disable-xdg.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 8809, child pid 8810
10 programs installed in 94.31 ms
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 173.08 ms
/home/wonbug/Browser/start-tor-browser: line 85: id: command not found
/home/wonbug/Browser/start-tor-browser: line 85: [: : integer expression expected

Parent is shutting down, bye...
```

The browser doesn't start. I've worked around this issue before by using the version of firejail from HEAD, but this breaks other stuff and I don't want to do that anymore.

Thanks for taking a look at the issue.

**Comment by rusty-snake** [comment]
Yes, if you use 0.9.64.4 you need to pass `--firejail=0.9.64.4`.

Is there anything other than `include firejailed-tor-browser-x11.inc` in `firejailed-tor-browser.local`? I assume no.

Is there any error logged in your syslog?

**Comment by wonbug** [comment]
Same result running install.sh with that flag.

Correct - only that line in the file.

No messages in /var/log/syslog - anywhere else to check?

Thank you for your help.

**Comment by rusty-snake** [comment]
> No messages in /var/log/syslog - anywhere else to check?

`journalctl`

If this does not bring up any error message you need to start to comment stuff in `firejailed-tor-browser.profile` (but not `private ${HOME}/.firejailed-tor-browser`). W/o an error message I've no idea.

**Comment by wonbug** [comment]
Nothing in `journalctl` at all. The profile file is identical to another Debian 11.3 installation I did which works fine, so I suspect the issue is with my system. Both have apparmor on and selinux enabled.

I went through and removed options one by one until I found the culprit - it appears to be `hostname host`. If I remove that line, the browser will start.

**Comment by rusty-snake** [comment]
Makes sense if you still stick to X11. We will need to add `ignore hostname` to `firejailed-tor-browser-x11.inc`.

**Comment by wonbug** [comment]
Thanks. Any security/privacy considerations to be aware of when removing that directive?

**Comment by rusty-snake** [comment]
> Any security/privacy considerations to be aware of when removing that directive?

No.

**Comment by wonbug** [comment]
@rusty-snake I'm having the exact same issue on a fresh installation of Debian 11.6 and tor-browser version 12.0.2

I first tried using firejail from apt, then compiled the latest source and installed firejailed-tor-browser with `--firejail=0.9.70`

I confirmed `ignore hostname` is in `firejailed-tor-browesr-x11.inc` and this workaround doesn't appear to help.

Anything else I could try? Thank you!

**Comment by rusty-snake** [comment]
Just to be sure, `firejailed-tor-browesr-x11.inc` is included?

If you install firejail from git, you do not have to specify an stable version via `--firejail=`.

If nothing helps and we don't have an error, the good old trial and error method will likely help us.

**Comment by wonbug** [comment]
Confirmed, `include firejailed-tor-browser-x11.inc` is the only line in `~/.config/firejail/firejailed-tor-browser.local`

I tried whacking `firejailed-tor-browser.profile` line by line but no dice. Is there any other file to try trimming?

**Comment by rusty-snake** [comment]
If `firejail --profile=firejailed-tor-browser /home/wonbug/Browser/start-tor-browser` fails with an empty `firejailed-tor-browser.profile` (and no error), it's getting complicated. Does it show something if you run `firejail --noprofile /home/wonbug/Browser/start-tor-browser --help`?

**Comment by wonbug** [comment]
The file cannot be empty or I get an error saying the executable can't be found. However, I managed to narrow it down to these lines:

```
whitelist /usr/share/glib-2.0/schemas/gschemas.compiled
whitelist /usr/share/icons/Adwaita
whitelist /usr/share/mime/magic
whitelist /usr/share/misc/magic
whitelist /usr/share/X11/xkb
```

Without them, FTB starts. But if even one of them is in the profile, it will fail to launch.

**Comment by rusty-snake** [comment]
Ok, then add `include whitelist-usr-share-common.inc` to fix it until we find which path is necessary under debian.

**Comment by wonbug** [comment]
That works also, thank you!

For some reason, connections on this system (compared to other *nix ones on the same network) are consistently much, much slower than usual and about 3/4 of the sessions just time out and don't work altogether. Could this by affected by the profile at all? I'm using the same connection settings (obfs4 bridge) on all the systems.

Edit: nevermind, looks like Coreboot systems share the same MAC address, so that was causing the networking problem as I was updating this issue.
