### ISSUE TITLE
FTB won't start

### ISSUE THREAD

**Issue by samsapti** [rusty-snake/firejailed-tor-browser#38]
Suddenly, out of nothing seemingly, FTB won't start anymore. It didn't get any updates or anything, and Firejail wasn't updated.

Running FTB with `--profile=noprofile` works fine.

When running with `firejail --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"`, it just segfaults and exits. This is what pops up in my syslog:

```log
Nov 29 20:56:09 4rt1x kernel: audit: type=1326 audit(1669751769.123:135): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=27970 comm="firefox.real" exe="/home/sam/Browser/firefox.real" sig=31 arch=c000003e syscall=173 compat=0 ip=0x7f08f0320bcb code=0x0
Nov 29 20:56:09 4rt1x kernel: audit: type=1326 audit(1669751769.169:136): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=27965 comm=4E65746C696E6B204D6F6E69746F72 exe="/home/sam/Browser/firefox.real" sig=0 arch=c000003e syscall=41 compat=0 ip=0x7f08f0322f6b code=0x50000
```

When running Firejail with the `--debug` flag, the syslog looks like this:

```log
Nov 29 20:55:53 4rt1x firejail[27582]: firejail --debug --profile=firejailed-tor-browser /home/sam/Browser/start-tor-browser
Nov 29 20:55:53 4rt1x firejail[27583]: monitoring pid 19
Nov 29 20:55:53 4rt1x kernel: audit: type=1326 audit(1669751753.869:131): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=27633 comm="firefox.real" exe="/home/sam/Browser/firefox.real" sig=31 arch=c000003e syscall=173 compat=0 ip=0x7f1220c38bcb code=0x0
Nov 29 20:55:53 4rt1x kernel: audit: type=1326 audit(1669751753.923:132): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=27623 comm=4E65746C696E6B204D6F6E69746F72 exe="/home/sam/Browser/firefox.real" sig=0 arch=c000003e syscall=41 compat=0 ip=0x7f1220c3af6b code=0x50000
Nov 29 20:55:53 4rt1x firejail[27582]: exiting...
```

Firejail version is 0.9.70, running on Artix Linux under Wayland (Sway). FTB was installed with `./install.sh --firejail=git`.

Last time it worked was yesterday, 2022-11-28, and the only packages that were upgraded since then are:

- `btrfs-progs`
- `esysusers`
- `etmpfiles`
- `iputils`
- `libudev`
- `luajit`
- `python-pipenv`
- `ruby-bundler`
- `udev`

None of them seem to have anything to do with Firejail.

Output of `firejail --debug --profile=firejailed-tor-browser "$HOME/Browser/start-tor-browser"` attached.

[debug.txt](https://github.com/rusty-snake/firejailed-tor-browser/files/10116932/debug.txt)

**Comment by rusty-snake** [comment]
Can you try to add `netlink` to the protocol list.

**Comment by samsapti** [comment]
Still the same outcome.

**Comment by samsapti** [comment]
Still segfaulting, but the syslog looks a bit different (still with `--debug`):

```log
Nov 29 21:28:22 4rt1x firejail[23006]: firejail --debug --profile=firejailed-tor-browser /home/sam/Browser/start-tor-browser
Nov 29 21:28:22 4rt1x firejail[23008]: monitoring pid 19
Nov 29 21:28:22 4rt1x kernel: audit: type=1326 audit(1669753702.610:78): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=23042 comm="firefox.real" exe="/home/sam/Browser/firefox.real" sig=31 arch=c000003e syscall=173 compat=0 ip=0x6e7a2c438bcb code=0x0
Nov 29 21:28:22 4rt1x firejail[23006]: exiting...
```

Specifically, this line is absent now:

```log
Nov 29 20:55:53 4rt1x kernel: audit: type=1326 audit(1669751753.923:132): auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined pid=27623 comm=4E65746C696E6B204D6F6E69746F72 exe="/home/sam/Browser/firefox.real" sig=0 arch=c000003e syscall=41 compat=0 ip=0x7f1220c3af6b code=0x50000
```

**Comment by rusty-snake** [comment]
Ok then is this not the cause. I've no idea, so comment the profile line for line to find the problem.

**Comment by rusty-snake** [comment]
Correction, seems to be `read-only ${RUNUSER}`.

**Comment by samsapti** [comment]
> Correction, seems to be `read-only ${RUNUSER}`.

Yep, that's my conclusion as well. Changing it to `read-write` fixes it.

**Comment by samsapti** [comment]
But it's weird that it suddenly changed behavior overnight. Did you experience the same behavior, or how did you found out?

**Comment by rusty-snake** [comment]
Yes, same behaviour but I tried first with debugging (strace, ...) and wasn't wondered about crashes when using strace on TB so it took some time to realizes it is crashing even without.

**Comment by samsapti** [comment]
Anyway, thanks for the help.

**Comment by rusty-snake** [comment]
Looking at the strace it could be related to gdk/wayland with makes sense in that way that the wayland socket is in `${RUNUSER}`.

**Comment by samsapti** [comment]
That does make sense. Still doesn't make sense how it has worked without problems until today.
