### ISSUE TITLE
Problems downloading files

### ISSUE THREAD

**Issue by samsapti** [rusty-snake/firejailed-tor-browser#43]
I'm having problems downloading certain files when TBB is Firejailed. One example is the "Download Files" button in OnionShare links, such as [this one with Tor wallpapers](http://onionshare:dealing-corridor@hqcvwpnlspoxj2yoem5vavskgmy52tiwrilh7wxcgzvoidlxxxbd34qd.onion) from The Tor Project. It only occours with files where TBB normally creates a pop-up that says:

```
Tor Browser cannot display this file. You will need to open it with another application.

Some types of files can cause applications to connect to the Internet without using Tor.

To be safe, you should only open downloaded files while offline, or use a Tor Live CD such as Tails.
```

Instead, it shows no pop-up, but adds the file to the download queue and instantly fails to download.

**Comment by rusty-snake** [comment]
May guess would be that adding either

```
ignore read-only ${HOME}
```
or
```
noblacklist /tmp
private-tmp
```
to `firejailed-tor-browser.local` should make it work. Can you try and report back.

**Comment by samsapti** [comment]
The first one didn't work, but the second one did. Thanks!
